language: python
python:
  - "3.6"
services:
  - mysql
before_install:
  - sudo apt-get install python-mysqldb
  - echo "CREATE SCHEMA test" | mysql -u root
install:
  - pip install .
script:
  - python setup.py test
